import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // ============================================
  // AUTHORS — Personnalités éditoriales fixes
  // ============================================
  authors: defineTable({
    // Identité
    name: v.string(),
    slug: v.string(),
    avatar: v.string(),
    bio: v.string(),
    
    // Spécialisation
    categories: v.array(v.string()),
    expertise: v.array(v.string()),
    
    // Personnalité éditoriale (injecté dans le prompt Claude)
    writingStyle: v.string(),
    tone: v.string(), // "analytique" | "engagé" | "narratif" | "investigation" | "vulgarisation"
    signaturePhrase: v.optional(v.string()),
    
    // Exemples de style (few-shot pour Claude)
    sampleIntro: v.string(),
    sampleConclusion: v.string(),
    
    // Métadonnées
    isActive: v.boolean(),
    articleCount: v.number(),
    createdAt: v.number(),
  })
    .index("by_slug", ["slug"])
    .index("by_active", ["isActive"]),

  // ============================================
  // CATEGORIES
  // ============================================
  categories: defineTable({
    name: v.string(),
    slug: v.string(),
    description: v.optional(v.string()),
    color: v.optional(v.string()),
    sortOrder: v.number(),
    isActive: v.boolean(),
    createdAt: v.number(),
  })
    .index("by_slug", ["slug"])
    .index("by_order", ["sortOrder"]),

  // ============================================
  // ARTICLES
  // ============================================
  articles: defineTable({
    // Identifiants
    slug: v.string(),
    
    // Contenu
    title: v.string(),
    excerpt: v.string(),
    content: v.string(),
    aiSummary: v.optional(v.string()),
    
    // Images
    images: v.array(v.object({
      url: v.string(),
      caption: v.string(),
      credit: v.string(),
      isHero: v.boolean(),
    })),
    
    // Legacy (compatibilité)
    imageUrl: v.optional(v.string()),
    
    // Classification
    categoryId: v.id("categories"),
    tags: v.array(v.string()),
    isFeatured: v.boolean(),
    
    // Auteur
    authorId: v.id("authors"),
    authorName: v.string(),
    
    // Source & Traçabilité
    sourceUrl: v.string(),
    sourceName: v.string(),
    originalLanguage: v.string(), // "en" | "fr" | "pt" | "ar"
    isTranslated: v.boolean(),
    
    // Métriques de lecture
    readingTime: v.number(),
    viewsCount: v.number(),
    likesCount: v.number(),
    recommendsCount: v.number(),
    usefulCount: v.number(),
    commentsCount: v.number(),
    
    // Workflow de publication
    status: v.string(), // "draft" | "pending_review" | "published" | "rejected"
    publishedAt: v.optional(v.number()),
    reviewedAt: v.optional(v.number()),
    rejectionReason: v.optional(v.string()),
    
    // Auto-génération
    isAutoGenerated: v.boolean(),
    generationModel: v.optional(v.string()),
    
    // Dates
    createdAt: v.number(),
    updatedAt: v.number(),
    
    // SEO
    metaTitle: v.optional(v.string()),
    metaDescription: v.optional(v.string()),
  })
    .index("by_slug", ["slug"])
    .index("by_category", ["categoryId"])
    .index("by_author", ["authorId"])
    .index("by_status", ["status"])
    .index("by_published", ["publishedAt"])
    .index("by_views", ["viewsCount"])
    .index("by_featured", ["isFeatured"]),

  // ============================================
  // ARTICLE VIEWS (tracking)
  // ============================================
  articleViews: defineTable({
    articleId: v.id("articles"),
    viewerIp: v.optional(v.string()),
    userId: v.optional(v.string()),
    viewedAt: v.number(),
  })
    .index("by_article", ["articleId"]),

  // ============================================
  // ARTICLE LIKES
  // ============================================
  articleLikes: defineTable({
    articleId: v.id("articles"),
    visitorId: v.string(),
    createdAt: v.number(),
  })
    .index("by_article", ["articleId"])
    .index("by_article_visitor", ["articleId", "visitorId"]),

  // ============================================
  // ARTICLE REACTIONS (recommends, useful)
  // ============================================
  articleReactions: defineTable({
    articleId: v.id("articles"),
    visitorId: v.string(),
    type: v.string(), // "recommend" | "useful"
    createdAt: v.number(),
  })
    .index("by_article", ["articleId"])
    .index("by_article_visitor_type", ["articleId", "visitorId", "type"]),

  // ============================================
  // COMMENTS
  // ============================================
  comments: defineTable({
    articleId: v.id("articles"),
    userId: v.optional(v.string()),
    authorName: v.string(),
    content: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_article", ["articleId"]),

  // ============================================
  // NEWSLETTER SUBSCRIBERS
  // ============================================
  subscribers: defineTable({
    email: v.string(),
    createdAt: v.number(),
  })
    .index("by_email", ["email"]),

  // ============================================
  // CONTACT MESSAGES
  // ============================================
  contactMessages: defineTable({
    name: v.string(),
    email: v.string(),
    subject: v.optional(v.string()),
    message: v.string(),
    createdAt: v.number(),
  }),

  // ============================================
  // SCRAPING LOGS (traçabilité pipeline)
  // ============================================
  scrapingLogs: defineTable({
    source: v.string(),           // "Africa Newsroom", "BAD", etc.
    sourceUrl: v.string(),
    title: v.string(),
    status: v.string(),           // "scraped" | "processed" | "published" | "rejected" | "duplicate"
    articleId: v.optional(v.id("articles")),
    errorMessage: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("by_source", ["source"])
    .index("by_status", ["status"])
    .index("by_url", ["sourceUrl"]),
});
